/* app.js — Main controller, UI helpers, Exporter */

// ── UI ────────────────────────────────────────────────────────────────────────

const UI = (() => {
  let _toastTimer    = null;
  let _settingsOpen  = false;
  let _historyOpen   = false;

  function toast(msg, type = 'info') {
    const el = document.getElementById('toast');
    if (!el) return;
    el.textContent = msg;
    el.className = `toast toast-${type} visible`;
    clearTimeout(_toastTimer);
    _toastTimer = setTimeout(() => el.classList.remove('visible'), 3500);
  }

  function toggleSettings() {
    _settingsOpen = !_settingsOpen;
    document.getElementById('settings-panel')?.classList.toggle('hidden', !_settingsOpen);
  }
  function closeSettings() {
    _settingsOpen = false;
    document.getElementById('settings-panel')?.classList.add('hidden');
  }
  function toggleHistory() {
    _historyOpen = !_historyOpen;
    document.getElementById('history-panel')?.classList.toggle('hidden', !_historyOpen);
  }
  function closeHistory() {
    _historyOpen = false;
    document.getElementById('history-panel')?.classList.add('hidden');
  }

  function setRunning(is) {
    const btn = document.getElementById('run-btn');
    if (!btn) return;
    btn.disabled = is;
    btn.innerHTML = is ? '<span class="spinner"></span>Running…' : '▶ Run';
  }

  function setBadge(id, visible) {
    document.getElementById(id)?.classList.toggle('hidden', !visible);
  }

  return { toast, toggleSettings, closeSettings, toggleHistory, closeHistory, setRunning, setBadge };
})();

// ── Exporter ──────────────────────────────────────────────────────────────────

const Exporter = (() => {
  function toC() {
    let code = Editor.getValue();
    if (!code) {
      const pre = document.querySelector('#output-content .code-block pre');
      if (pre) code = pre.innerText;
    }
    if (!code) { UI.toast('No C code to export', 'warn'); return; }

    const header = `/* Generated by C Code Assistant — ${new Date().toLocaleString()} */\n\n`;
    const full   = code.startsWith('/*') ? code : header + code;
    const blob   = new Blob([full], { type: 'text/x-csrc' });
    const url    = URL.createObjectURL(blob);
    const a      = Object.assign(document.createElement('a'), { href: url, download: `code_${Date.now()}.c` });
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    UI.toast('Exported .c file', 'ok');
  }
  return { toC };
})();

// ── App ───────────────────────────────────────────────────────────────────────

const App = (() => {
  let _mode = 'complete';

  const MODE_LABELS = {
    complete: 'Code Completion',
    generate: 'Generate Code',
    explain:  'Explain Code',
    fix:      'Fix / Debug',
    optimize: 'Optimize',
  };

  const MODE_HINTS = {
    complete: '// Write partial C code — the model will complete it…\n// Ctrl+Enter to run',
    generate: 'Describe what you want in plain English:\ne.g. "A program that checks if a number is palindrome"',
    explain:  '// Paste C code you want explained…',
    fix:      '// Paste buggy C code — all bugs will be found and fixed…',
    optimize: '// Paste C code to optimize for speed or memory…',
  };

  function init() {
    Config.load();
    History.load();
    Editor.init();

    // Wire editor input → line numbers + auto-lint
    document.getElementById('code-input')?.addEventListener('input', () => {
      Editor.updateLineNumbers();
      Linter.scheduleAuto();
    });

    // Close settings on outside click
    document.addEventListener('click', e => {
      if (!e.target.closest('#settings-panel') && !e.target.closest('#settings-toggle'))
        UI.closeSettings();
    });

    // Close custom model modal on overlay click
    document.getElementById('custom-model-modal')?.addEventListener('click', e => {
      if (e.target.id === 'custom-model-modal') ModelSwitcher.cancelCustom();
    });

    // Enter in custom model input
    document.getElementById('custom-model-input')?.addEventListener('keydown', e => {
      if (e.key === 'Enter') ModelSwitcher.confirmCustom();
      if (e.key === 'Escape') ModelSwitcher.cancelCustom();
    });

    setMode('complete');
    checkConnections();
    _setStat('stat-queries', 0);
  }

  function setMode(mode) {
    _mode = mode;
    document.querySelectorAll('.mode-btn').forEach(btn =>
      btn.classList.toggle('active', btn.dataset.mode === mode));

    const lbl = document.getElementById('input-mode-label');
    if (lbl) lbl.textContent = MODE_LABELS[mode] || mode;

    const ta = document.getElementById('code-input');
    if (ta && !ta.value.trim()) ta.placeholder = MODE_HINTS[mode] || '';
  }

  function currentMode() { return _mode; }

  async function run() {
    const input = Editor.getValue();
    if (!input) { UI.toast('Please enter code or a description first', 'warn'); return; }

    UI.setRunning(true);
    UI.setBadge('stream-badge', true);
    UI.setBadge('retry-badge',  false);
    UI.setBadge('compile-badge',false);
    Output.clear();
    Compiler.clear();

    _setStat('stat-queries', parseInt(document.getElementById('stat-queries')?.textContent || '0') + 1);

    await API.run(_mode, input, {
      onChunk(partial) {
        Output.render(partial, true);
        UI.setBadge('stream-badge', true);
        UI.setBadge('retry-badge',  false);
      },

      onRetry(attempt, max, phase) {
        if (phase === 'checking') {
          UI.setBadge('stream-badge', false);
          UI.setBadge('retry-badge',  true);
        } else if (phase === 'retrying') {
          UI.toast(`Quality check failed — retrying (${attempt}/${max})…`, 'warn');
          UI.setBadge('retry-badge',  true);
          UI.setBadge('stream-badge', false);
          Output.clear();
        }
      },

      onDone(finalOutput, quality) {
        UI.setBadge('stream-badge', false);
        UI.setBadge('retry-badge',  false);
        UI.setRunning(false);
        Output.finalize(finalOutput, quality);

        if (quality.pass) {
          UI.toast(`✓ Done (${quality.attempts} attempt${quality.attempts > 1 ? 's' : ''})`, 'ok');
        } else {
          UI.toast(`⚠ Best-effort after ${quality.attempts} retries — review output`, 'warn');
        }

        History.push({
          mode:      _mode,
          input,
          output:    finalOutput,
          quality:   quality.pass ? 'pass' : 'fail',
          timestamp: Date.now(),
        });
      },

      onError(msg) {
        UI.setBadge('stream-badge', false);
        UI.setBadge('retry-badge',  false);
        UI.setRunning(false);

        const hint = (msg.includes('fetch') || msg.includes('Failed') || msg.includes('NetworkError'))
          ? '<br><br>Make sure Ollama is running:<br><code>set OLLAMA_ORIGINS=*<br>ollama serve</code>'
          : '';

        const content = document.getElementById('output-content');
        document.getElementById('output-placeholder')?.classList.add('hidden');
        if (content) {
          content.classList.remove('hidden');
          content.innerHTML = `<div style="color:var(--red);font-family:var(--font-mono);font-size:12px;line-height:1.9">
            <strong>Error</strong><br>${_esc(msg)}${hint}</div>`;
        }
        UI.toast(msg.slice(0, 80), 'error');
      },
    });
  }

  let _retryTimer = null;

  async function checkConnections() {
    clearTimeout(_retryTimer);

    // ── Ollama ──────────────────────────────────────────────────────────────
    const odot = document.getElementById('ollama-dot');
    const otxt = document.getElementById('ollama-text');
    const mdot = document.getElementById('model-dot');
    const tag  = document.getElementById('model-tag');

    if (odot) odot.className = 'dot';
    if (otxt) otxt.textContent = 'Checking…';

    try {
      const res = await API.checkOllama();

      if (res.ok) {
        const model = Config.get('model');

        // Refresh dropdown with live model list
        ModelSwitcher.fetchInstalled();

        // Check if selected model is actually installed
        const found = res.models.some(m =>
          m.toLowerCase() === model.toLowerCase() ||
          m.toLowerCase().startsWith(model.split(':')[0].toLowerCase())
        );

        if (found) {
          if (odot) odot.className = 'dot online';
          if (otxt) otxt.textContent = 'Ollama online';
          if (mdot) { mdot.style.background = 'var(--green)'; mdot.style.boxShadow = '0 0 6px var(--green)'; }
          if (tag)  { tag.textContent = 'active'; tag.style.color = 'var(--green)'; tag.style.background = 'rgba(52,212,142,0.12)'; }
        } else {
          // Ollama is online but this model is not pulled
          if (odot) odot.className = 'dot online';   // Ollama itself IS online
          if (otxt) otxt.textContent = 'Ollama online';
          if (mdot) { mdot.style.background = 'var(--amber)'; mdot.style.boxShadow = '0 0 6px var(--amber)'; }
          if (tag)  { tag.textContent = 'not pulled'; tag.style.color = 'var(--amber)'; tag.style.background = 'rgba(245,166,35,0.12)'; }
          UI.toast(
            'Model "' + model + '" is not installed.\n' +
            'Run in terminal:  ollama pull ' + model + '\n' +
            'Available: ' + res.models.slice(0, 4).join(', '),
            'warn'
          );
        }
      } else {
        _setOllamaOffline(odot, otxt, mdot, tag, res.reason || '');
      }
    } catch (e) {
      _setOllamaOffline(odot, otxt, mdot, tag, e.message || '');
    }

    // Auto-retry every 12 seconds until online
    const isOnline = odot && odot.className.includes('online');
    if (!isOnline) {
      _retryTimer = setTimeout(checkConnections, 12000);
    }

    // ── Backend ─────────────────────────────────────────────────────────────
    const bdot = document.getElementById('backend-dot');
    const btxt = document.getElementById('backend-text');
    if (bdot) bdot.className = 'dot';
    if (btxt) btxt.textContent = 'Checking…';

    API.checkBackend().then(res => {
      if (res.ok) {
        if (bdot) bdot.className = 'dot online';
        if (btxt) btxt.textContent = 'Backend online' + (res.cppcheck ? ' + cppcheck' : '');
      } else {
        if (bdot) bdot.className = 'dot error';
        if (btxt) btxt.textContent = 'Backend offline — run: python server.py';
      }
    }).catch(() => {
      if (bdot) bdot.className = 'dot error';
      if (btxt) btxt.textContent = 'Backend offline';
    });
  }

  function _setOllamaOffline(odot, otxt, mdot, tag, reason) {
    if (odot) odot.className = 'dot error';
    if (mdot) { mdot.style.background = 'var(--muted)'; mdot.style.boxShadow = 'none'; }
    if (tag)  { tag.textContent = 'offline'; tag.style.color = 'var(--muted)'; tag.style.background = 'transparent'; }
    if (otxt) otxt.textContent = 'Ollama offline';
    UI.toast(
      'Ollama is not running.\n\n' +
      'Start it with:\n  ollama serve\n\n' +
      '(Retrying in 12s…)',
      'error'
    );
  }

  function _setStat(id, val) {
    const el = document.getElementById(id);
    if (el) el.textContent = val;
  }

  function _esc(s) {
    return String(s)
      .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
      .replace(/\n/g,'<br>');
  }

  return { init, setMode, currentMode, run, checkConnections };
})();

document.addEventListener('DOMContentLoaded', App.init);
